using System;

namespace FPTU.Capstone.AMKCollective.Domain.Entities
{
    /// <summary>
    /// Generic base entity with configurable primary key type.
    /// Use int for high-volume, internal entities (better performance).
    /// Use Guid for security-sensitive, public-facing entities.
    /// </summary>
    public abstract class BaseEntity<TKey> where TKey : struct
    {
        public TKey Id { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public Guid? CreatedBy { get; set; }
        public Guid? UpdatedBy { get; set; }
        public bool IsDeleted { get; set; } = false;

        protected BaseEntity()
        {
            CreatedAt = DateTime.UtcNow;
        }
    }

    /// <summary>
    /// Base entity with Guid primary key (default for most entities).
    /// Use for: User, Order, Payment, ShopProfile - security sensitive, public facing.
    /// </summary>
    public abstract class BaseEntity : BaseEntity<Guid>
    {
        protected BaseEntity() : base()
        {
            Id = Guid.NewGuid();
        }
    }

    /// <summary>
    /// Base entity with int primary key (auto-increment).
    /// Use for: CommunityPost, Comment, Reaction, Message, Notification - high volume, internal.
    /// Benefits: 75% less storage, better index performance, sequential inserts.
    /// </summary>
    public abstract class BaseEntityInt : BaseEntity<int>
    {
        protected BaseEntityInt() : base()
        {
            // Id will be auto-generated by database
        }
    }
}
